spring:
  profiles:
    active: default
  application:
    name: spring security 05
  thymeleaf:
    cache: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:spring_security;MODE=MYSQL;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#    hikari:
#      minimum-idle: 1
#      maximum-pool-size: 5
#      pool-name: H2_DB
#  sql:
#    init:
#      platform: h2
#      schema-locations: classpath:sql/schema_new.sql
#      data-locations: classpath:sql/data_new.sql
#      encoding: UTF-8
server:
  ssl:
    enabled: true
    key-alias: prgrms_keystore
    key-store: classpath:prgrms_keystore.p12
    key-store-password: 1q2w3e4r
    key-password: 1q2w3e4r
    trust-store: classpath:prgrms_truststore.p12
    trust-store-password: 1q2w3e4r
  port: 8443