spring:
  application:
    name: spring security 02
  thymeleaf:
    cache: true
  security:
    user:
      name: user
      password: user123
      roles: USER
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
server:
  ssl:
    enabled: true
    key-alias: prgrms_keystore
    key-store: classpath:prgrms_keystore.p12
    key-store-password: 1q2w3e4r
    key-password: 1q2w3e4r
    trust-store: classpath:prgrms_truststore.p12
    trust-store-password: 1q2w3e4r